@php
    $selectedCompanies = (array) old('company_id', $designation?->company_id ?? []);
    $selectedLocations = (array) old('location_id', $designation?->location_id ?? []);
    $selectedCategories = (array) old('category_id', $designation?->category_id ?? []);
@endphp
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Basic Information</h5></div><div class="card-body"><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Designation Name *</label><input name="name" class="form-control" value="{{ old('name', $designation?->name) }}" required></div><div class="col-md-6 mb-3"><label class="form-label">Designation Code *</label><input name="code" class="form-control" value="{{ old('code', $designation?->code) }}" required></div></div></div></div>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Organization</h5></div><div class="card-body"><div class="row"><div class="col-md-4 mb-3"><label class="form-label">Companies</label><select name="company_id[]" class="form-control select2" multiple>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(in_array($company->id, $selectedCompanies))>{{ $company->name }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Locations</label><select name="location_id[]" class="form-control select2" multiple>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(in_array($location->id, $selectedLocations))>{{ $location->name }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">Categories</label><select name="category_id[]" class="form-control select2" multiple>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id, $selectedCategories))>{{ $category->name }}</option>@endforeach</select></div></div></div></div>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Configuration</h5></div><div class="card-body"><label class="form-label">Status *</label><select name="status" class="form-control" required><option value="1" @selected(old('status', $designation?->status ?? 1) == 1)>Active</option><option value="0" @selected(old('status', $designation?->status ?? 1) == 0)>Inactive</option></select></div></div>
