@extends('layout.mainlayout')
@section('content')
@php
	$canCreate = \App\Support\TenantPermissions::userCan('CanteenFacility', 'create');
	$canImport = \App\Support\TenantPermissions::userCan('CanteenFacility', 'import');
	$canExport = \App\Support\TenantPermissions::userCan('CanteenFacility', 'export');
@endphp
<div class="page-wrapper"><div class="content">
	@include('partials.flash-alerts')
	<div class="d-md-flex d-block align-items-center justify-content-between page-breadcrumb mb-3"><div class="my-auto mb-2"><h2 class="mb-1">Canteen Facilities</h2><nav><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ url('index') }}"><i class="ti ti-smart-home"></i></a></li><li class="breadcrumb-item">Company Structure</li><li class="breadcrumb-item active">Canteen Facilities</li></ol></nav></div><div class="d-flex my-xl-auto right-content align-items-center flex-wrap">@if ($canExport)<div class="mb-2 me-2"><a href="{{ url('company-structure/canteen-facilities/export') }}" class="btn btn-light d-flex align-items-center"><i class="ti ti-file-export me-2"></i>Export</a></div>@endif @if ($canImport)<div class="mb-2 me-2"><button type="button" class="btn btn-light d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#import_canteen_facility_modal"><i class="ti ti-file-import me-2"></i>Import</button></div>@endif @if ($canCreate)<div class="mb-2"><a href="{{ url('company-structure/canteen-facilities/create') }}" class="btn btn-primary d-flex align-items-center"><i class="ti ti-circle-plus me-2"></i>Add Canteen Facility</a></div>@endif</div></div>
	<div id="canteen-facility-status-alert" class="alert alert-dismissible d-none align-items-center" role="alert"><i class="ti ti-circle-check me-2 alert-icon"></i><span class="alert-message"></span><button type="button" class="btn-close" aria-label="Close"></button></div>
	<div class="card"><div class="card-header d-flex align-items-center justify-content-between flex-wrap row-gap-3"><h5>Canteen Facility List</h5><div class="d-flex my-xl-auto right-content align-items-center flex-wrap row-gap-3"><div class="dropdown me-3"><a href="javascript:void(0);" class="dropdown-toggle btn btn-white d-inline-flex align-items-center" data-bs-toggle="dropdown">Status</a><ul class="dropdown-menu dropdown-menu-end p-3"><li><button type="button" class="dropdown-item rounded-1 canteen-facility-status-filter" data-status="all">All</button></li><li><button type="button" class="dropdown-item rounded-1 canteen-facility-status-filter" data-status="1">Active</button></li><li><button type="button" class="dropdown-item rounded-1 canteen-facility-status-filter" data-status="0">Inactive</button></li></ul></div></div></div><div class="card-body p-0"><div class="custom-datatable-filter table-responsive"><table class="table datatable"><thead class="thead-light"><tr><th class="no-sort"><div class="form-check form-check-md"><input class="form-check-input" type="checkbox" id="select-all"></div></th><th>Name</th><th>Code</th><th>Total CFA</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>@include('company-structure.canteen-facilities.partials.rows', ['canteenFacilities' => $canteenFacilities])</tbody></table></div></div>@if ($canteenFacilities->hasPages())<div class="card-footer d-flex align-items-center justify-content-between flex-wrap row-gap-2"><p class="mb-0 text-muted fs-13">Showing {{ $canteenFacilities->firstItem() }}-{{ $canteenFacilities->lastItem() }} of {{ $canteenFacilities->total() }} canteen facilities</p>{{ $canteenFacilities->links() }}</div>@endif</div>
</div>@include('partials.footer')</div>
<div class="modal fade" id="delete_canteen_facility_modal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-body text-center"><h4>Confirm Delete</h4><p id="delete_canteen_facility_message">Are you sure?</p><form id="delete_canteen_facility_form" method="POST">@csrf @method('DELETE')<button type="button" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</button><button class="btn btn-danger">Yes, Delete</button></form></div></div></div></div>
@if($canImport)<div class="modal fade" id="import_canteen_facility_modal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Import Canteen Facilities</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form method="POST" action="{{ url('company-structure/canteen-facilities/import') }}" enctype="multipart/form-data" data-import-form="true" data-status-alert="#canteen-facility-status-alert" data-modal="#import_canteen_facility_modal" data-url-match="/company-structure/canteen-facilities" data-entity-label="Canteen Facility">@csrf<div class="modal-body"><input name="file" type="file" class="form-control" accept=".csv,.txt" required><a href="{{ url('company-structure/canteen-facilities/import/sample') }}" class="d-inline-flex align-items-center mt-2"><i class="ti ti-download me-1"></i>Download Sample CSV</a><div class="form-check mt-3"><input class="form-check-input" type="checkbox" name="update_duplicate_records" id="update_canteen_facility_duplicates" value="1"><label class="form-check-label" for="update_canteen_facility_duplicates">Update Duplicate Records</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Import</button></div></form></div></div></div>@endif
@push('scripts')@include('partials.import-poll')<script>document.addEventListener('click',function(e){var b=e.target.closest('.delete-canteen-facility-btn');if(b){document.getElementById('delete_canteen_facility_form').action=b.dataset.url;document.getElementById('delete_canteen_facility_message').textContent='Are you sure you want to delete "'+b.dataset.name+'"?';}});document.querySelectorAll('.canteen-facility-status-filter').forEach(function(b){b.addEventListener('click',function(){fetch('{{ url('company-structure/canteen-facilities/filter') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({status:this.dataset.status})}).then(function(r){return r.json();}).then(function(data){document.querySelector('table.datatable tbody').innerHTML=data.html;});});});</script>@endpush
@endsection
